// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function twoFer(input) {
  var addressee = input !== undefined ? input : "you";
  return "One for " + (addressee + ", one for me.");
}

exports.twoFer = twoFer;
/* No side effect */
